<?php
/*
 +--------------------------------------------------------------------+
 | Copyright Rich Lott / Artful Robot. All rights reserved.           |
 |                                                                    |
 | This work is published under the GNU AGPLv3 license with some      |
 | permitted exceptions and without any warranty. For full license    |
 | and copyright information, see https://civicrm.org/licensing       |
 +--------------------------------------------------------------------+
 */
/**
 * Drupal module providing a block for the Fair Pay campaign by the Equality Trust.
 *
 * @see https://github.com/artfulrobot/et_ftse/
 * @author Rich Lott / Artful Robot
 *
 */

function et_ftse_block_info() {
  $blocks['et_ftse']['info'] = t('Fair Pay FTSE data dashboard');
  return $blocks;
}
function et_ftse_block_view($delta='') {
	$block = ['subject'=>'','content'=>''];
  if ($delta === 'et_ftse') {

    // We need to resolve the path to this module and use it to include JS
    // files but also to pass it in so that the JS code can fetch the pound
    // graphic.
    $path = drupal_get_path('module', 'et_ftse');
    drupal_add_js(['et_ftse' => ['path' => "/$path/"]], 'setting');
    // VueJS required.
    drupal_add_js("$path/vue.min.js");
    // Include our app
    drupal_add_js("$path/dist/bundle.js");
    // JS to boot the app
    $block['content'] = <<<HTML
<div id="et_ftse-app"></div>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    window.et_ftse = new ETFTSE(document.getElementById('et_ftse-app'), Drupal.settings.et_ftse.path);
  });
</script>
HTML;
  }
	return $block;
}
